name: Blob storage website CI

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name jinoption3sa --account-key vYW/U2XGsI5l9FUo2FM9oDwMZ+YTaaIl7SQlA5yuNJeM039JkTJLS+hSnjUxnno/J0U1R+tTO4c0+AStJVvEAA== -d '$web' -s .
            
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS1 }}
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name option3-cdn --name option3-cdn-endpoint --resource-group Option3

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
